### ISSUE TITLE
DBTool broken

### ISSUE THREAD

**Issue by PatricNox** [PatricNox/DatabaseSearcher#19]
After the MYSQL rewrite, the tool broke and is no longer working at all.

> Fatal error: Uncaught Error: Call to a member function fetch_array() on bool in /dbSearcher/dbSearcher.php:90 Stack trace: #0 /index.php(22): dbSearcher->dbs_search('teststringsearc...', 'tja', true) #1 {main} thrown in/dbSearcher/dbSearcher.php on line 90

Occoured after https://github.com/PatricNox/DatabaseSearcher/pull/17

**Comment by PatricNox** [comment]
@karate

**Comment by karate** [comment]
I cannot reproduce this. Can you provide some more info? Do you get the error when searching for a string that doesn't exist? On strict mode or not?

**Comment by PatricNox** [comment]
Seems to depend on which database I query towards, I'll get back to you through here if it happends again.

(I use this tool frequently in my work)
